apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    chart: headlamp
    targetRevision: "0.x.x"
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: "headlamp-bo.k3s.porrapatbo.site"
              paths:
                - path: /
                  type: Prefix
          tls:
            - hosts:
                - headlamp-bo.k3s.porrapatbo.site
              secretName: headlamp-tls
        persistentVolumeClaim:
          enabled: false
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
