apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ledger-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/boeing/go-ledger-x  # update to your GitHub URL
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ledger-x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
