---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: ledger-x
spec:
  encryptedData:
    password: AgAOX226NfoGvZd4AIuQ7Te9dIKmcacYwZAodWqDCqsb4hzsCv7OOKtEq6C1hs31cEjBUlsnvuojuubFhEL25ezrz77eITFuxkQvtYaVkArK8BMWu/oHjOqrQ7m6UmkFalIFbcPUKuN6l6VrJL5JfNKCg5Z356+1S6BiRvBOH+pofadeVx23/UrPz5fSp7KmzCtzCTPTbI8DZ/YIRvHXxOB8lMEFKFq0FdbfUj7QD69h+jXTVRaYpdrQGG/ta4C/4XtEWjSuueXidXuZC8AR+m4KDMJyQzsJgaepYjAYo5+jUKyS3r8q7Nm+PyeYBsyCSZ4TluZZAqrZK/9Tv2BCVYlh4R7HJGlF8AXfR1Ro7aH8s+RRIAYMLr4XaYqMGF3ECvN5GJ1Lqopy0ujwb13xtuONEqJatrFsbF94dXCNQS70sbq04OBRk3LWDOeJGtFQ/TEsiiAbjDABdw+GdzZ0hI0fLlBMLXXGy4ehAVLQirhlWmm+XtIiiU7Kvd4FApv3QMYgQCxAvsYApGKCe34q4cnXZAnSah6iBVFpy8o9UF6YXsLEc5NyYihkZUF2Q6Cn2qETd+OP9SY8eRJAe+tCfXcWKZJXFptDSMZZzTkd8N+x3qC/U1AmE8WqRxe8ojarbtZKZn8/pXO7Un6PXSTIE5GJN7w0+aTRqh7rmpxA6plrxm/TRKuVkOaTL/JNxfPjtMYyBQmD4Ypljyfna9G1I/uKo4oElC7qr2SxfOzQdXv38g==
    postgres-password: AgBuNNo3JMBLtJ8o5XTsCJqx1to2qMKU0Ac83EoIKcfyDXx9UDF19a0ZFrxih9jfIFkbV2mbvs9n9UmybAFzeEZ7CcBssoz09MD8CtCs+JXbGdHKtKC9GYMsPOCzyGYbU7+iXDp03/YvCIdU/SknQnIUh/gw9Abza1io0QOoVNg0Md19GSvqlkY0OORS1D2bZPU6nYlXs8E6Akvi7YVTz8a57tU4lhzZmqe7Y6xd/v2uoxrXHQP9qGSdYYIBP/45KrQjEzF4DabQpR9Au8NPFHY5gsm6US1Uwygk0THvo1kMNT3rjvYSuVIYGQDCYjCgFQaU4bCFc3Tk+4W1k5IQdTHdf8nu5jFc8rSqlj4Q7OndGD9xTWJrGN+EJxcloRuFY6bNDX5Z0/WSnJjjqk2arDM3HHhORPejkPazRAnE9cXThGZNsbqsrZ2Q73VvypilUijVP0yP1xl/R44r5qp5NqcQmHPKdctWU/NlymL7ddLQ29tpP7dVv5vqOR3gYVfgu90gVPbYR1hbuUtlivPn+FXfVW3KNmnFXrZSlqBZF/5WP17YwpdszIeIKllm0U0aWEHbCEOHBhFrilQlaqi3+2IdsnZrtYpsFmn49WPnKDrsOAIgedmp69BN9MTobDZAbIVGHtvpFpNsgNLKY92XAidWU+72qUZzbIloe4XGGgnpIk74ivxY4w/m24u89qAv2NMBaqmzvGIk2+6JIMSY3eSnoYDBGDo4Pq2gU3dzzW7/NQ==
  template:
    metadata:
      name: postgresql-secret
      namespace: ledger-x
